// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "MainPage": {
    "title": "Resources",
    "welcomeTitle": "Welcome to the fun GCP & AI fan site! 🎉",
    "welcomeText": "No strict rules or boring instructions here. This is a place for learning, fun, and small victories in the world of cloud technologies.",
    "whatYouWillFind": "What you'll find here:",
    "resourcesAndGuides": "A curated selection of resources, guides, and tools that might come in handy anytime.",
    "funContent": "Some fun content to make learning not only useful but also enjoyable 😎",
    "usefulLinks": "Useful links to various interesting resources, answers to frequently asked questions, and much more.",
    "fanInitiative": "This is a small fan initiative for everyone who wants to learn stress-free and enjoy the process.",
    "joinAndLearn": "Join in, learn, and have fun! 🚀"
  },
  "AboutPage": {
    "title": "About this fan site",
    "intro": "This site was created to help you explore GCP, AI, and related technologies in a fun and relaxed way.",
    "whyHere": "Why this site exists:",
    "funProject": "A fan project to make learning enjoyable and engaging.",
    "resources": "A curated selection of resources, guides, and tools for anyone.",
    "community": "A place to find answers to common questions and tips.",
    "note": "This is an unofficial site, just to make learning light and fun 😉"
  },
  "RecordForm": {
    "addRecord": "Add Record",
    "titleUA": "Title (UA)",
    "titleEN": "Title (EN)",
    "link": "Link",
    "imageUrl": "Image URL",
    "descriptionUA": "Short Description (UA)",
    "descriptionEN": "Short Description (EN)",
    "contentUA": "Full Description (UA)",
    "contentEN": "Full Description (EN)",
    "save": "Save"
  },
  "Menu": {
    "home": "Home",
    "about": "About",
    "test": "GCP Test",
    "questions": "GCP Questions",
    "zodiac-roles": "GCP Zodiac",
    "blog": "News",
    "trending": "Google Trends",
    "links": "Useful Links",
    "arcade-calculator": "Arcade Calculator"
  },
  "FAQ": {
    "Title": "Expanded Questions",
    "Description": "This page is inspired by an article on Medium. It contains questions from the original article as well as new questions and answers that may be helpful for your learning and practice. Whether you are just starting or seeking to deepen your knowledge, this resource will guide you in asking the right questions and finding useful answers.",
    "SearchPlaceholder": "Search questions...",
    "All": "All",
    "Loading": "Loading...",
    "NothingFound": "Nothing found.",
    "OriginalArticle": "Original article:"
  },
  "Footer": {
    "madeWithLove": "Made with love and coffee ☕",
    "privacyPolicy": "Privacy Policy",
    "termsOfUse": "Terms of Use"
  },
  "RolePage": {
    "instruction": "👉 Click on a dot or name to learn more about the GCP role",
    "category": "Category",
    "requirements": "Requirements",
    "services": "Services",
    "tools": "Tools",
    "platforms": "Platforms",
    "languages": "Languages",
    "none": "None",
    "responsibilities": "Responsibilities",
    "links": "Useful links",
    "documentation": "Documentation",
    "bestPractices": "Best Practices",
    "tutorials": "Tutorials"
  },
  "TrendingPage": {
    "title": "Google Trends — Ukraine",
    "intro": "Google Trends shows what Google users are searching for in real time and allows you to track popular queries by country, region, or category. You can analyze interest trends over time, compare multiple queries, and follow trends in news and social media.",
    "helpText": "This service helps marketers, journalists, researchers, and ordinary users better understand current events and popular topics. For detailed viewing and in-depth analysis, visit {link}.",
    "officialLinkText": "official Google Trends website",
    "fallbackTitle": "No data available",
    "fallbackDescription": "Unable to load trends. Please try again later.",
    "fallbackExtendedDescription": "The Google Trends service is temporarily unavailable. Usually, you can view the most popular search queries of Ukrainian users in real time, analyze interest dynamics, and find related news."
  },
  "QuizIntro": {
    "title": "GCP Career Matchmaker: Find Your Ideal Role!",
    "intro": "Have you ever wondered which role in the Google Cloud Platform world suits you best?",
    "about-1": "This quiz is based on the ",
    "about-2": " model, which helps identify your professional interests. Take the quiz to find your ideal role!",
    "start": "Start Quiz",
    "riasec": {
      "R": {
        "title": "Realistic",
        "description": "Hands-on work with infrastructure, server setup, and process automation in the cloud."
      },
      "I": {
        "title": "Investigative",
        "description": "Data analysis, working with BigQuery, machine learning, and optimizing GCP services."
      },
      "A": {
        "title": "Artistic",
        "description": "Creative development of cloud applications, architecture design, and UI/UX solutions."
      },
      "S": {
        "title": "Social",
        "description": "Collaborating with teams, user support, implementing solutions, and conducting GCP training."
      },
      "E": {
        "title": "Enterprising",
        "description": "Leadership in cloud projects, managing teams, and strategic planning on GCP."
      },
      "C": {
        "title": "Conventional",
        "description": "Documenting processes, monitoring services, and maintaining cloud standards and procedures."
      }
    }
  },
  "QuizResult": {
    "linkCopied": "Copied!",
    "congratulations": "Congratulations!",
    "yourResult": "Here is your result:",
    "mainProfile": "Your main profile",
    "additionalRoles": "Your additional roles",
    "descriptionUnavailable": "Description unavailable.",
    "noAdditionalRoles": "No additional roles",
    "retry": "Take again",
    "shareResult": "Share your result",
    "copyLink": "Copy the link or share it with friends!",
    "roles": {
      "CloudDigitalLeader": {
        "description": "You lead digital transformation, manage teams, and implement innovations."
      },
      "GenerativeAILeader": {
        "description": "You manage AI and generative model projects."
      },
      "GoogleWorkspaceAdministrator": {
        "description": "You manage Google Workspace services for a team or organization."
      },
      "CloudDeveloper": {
        "description": "You develop diverse applications, write code, and build functional solutions."
      },
      "StartupCloudEngineer": {
        "description": "You quickly implement cloud solutions for startups and innovations."
      },
      "DataAnalyst": {
        "description": "You analyze data, create reports, and help the business make decisions."
      },
      "DevOpsEngineer": {
        "description": "You automate development and delivery processes, integrate CI/CD."
      },
      "APIDeveloper": {
        "description": "You specialize in integrations and APIs, solving complex technical tasks."
      },
      "ContactCenterEngineer": {
        "description": "You ensure stable operation of contact centers and communication systems."
      },
      "SecurityEngineer": {
        "description": "You protect systems, find vulnerabilities, and implement security measures."
      },
      "NetworkEngineer": {
        "description": "You configure networks, ensure security and connection stability."
      },
      "DatabaseEngineer": {
        "description": "You manage databases, optimize performance and reliability."
      },
      "CloudArchitect": {
        "description": "You design cloud architectures, optimize systems, and manage scaling."
      },
      "HybridMultiCloudArchitect": {
        "description": "You design hybrid and multi-cloud solutions for complex systems."
      },
      "MachineLearningEngineer": {
        "description": "You build ML models and integrate them into products."
      },
      "CloudEngineer": {
        "description": "You are a practical cloud systems engineer, setting up and maintaining infrastructure."
      },
      "CitizenDeveloper": {
        "description": "You create no-code solutions and help automate business processes."
      },
      "DataEngineer": {
        "description": "You build data pipelines and ensure data quality for analytics and ML."
      }
    }
  },
  "About": {
    "title": "About the Project 🌌",
    "intro": "This is an unofficial fan project created to help you better understand GCP, AI, and related technologies in an accessible and relaxed way. The visual design in the style of a starry and cloudy sky symbolizes cloud services that \"float\" in the digital space, opening new opportunities for learning and experiments. That’s where the playful name SkyNet comes from.",
    "responsibility": "Today, many discoveries happen thanks to AI. At the same time, it’s important to remember responsible use of technology, because without proper control it may have unpredictable consequences. 😎",
    "friendly": "Our SkyNet is exclusively friendly and educational. It helps you dive into the world of GCP, AI, and cloud services, creating a space for experiments and easy learning. And let the scenes from “Terminator” stay only in the movies — because smart and safe use of AI brings nothing but benefits.",
    "whyTitle": "Why this matters:",
    "whyList": {
      "one": "A fan project that makes learning easy and fun.",
      "two": "A collection of resources, guides, and tools for users of all levels.",
      "three": "A place to answer common questions and share helpful tips.",
      "four": "An unofficial website that creates a friendly atmosphere for learning 😉"
    }
  },
  "GoogleBlogWidget": {
    "title": "✨ Google News ✨",
    "description": "Get the latest news and updates directly from Google’s official blogs. Here you’ll find important announcements, helpful tips, and inspiring stories about products and technologies that have changed the world.",
    "uaBlog": "There is also the official Google Ukraine blog, where you can be the first to get updates! Click here",
    "googleUa": "Ukraine"
  }
};
export default messages;