import type {Metadata} from 'next';
import {Roboto, Roboto_Mono} from 'next/font/google';
import './globals.css';
import {ThemeProvider} from 'next-themes';
import Header from '@/components/Header';
import ThemeBackground from "@/components/ThemeBackground";
import {NextIntlClientProvider} from 'next-intl';

const roboto = Roboto({variable: '--font-roboto', subsets: ['latin'], weight: ['400', '700']});
const robotoMono = Roboto_Mono({variable: '--font-roboto-mono', subsets: ['latin'], weight: ['400', '700']});

export const metadata: Metadata = {
    title: 'SkyNet App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                       params,
                                   }: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    return (
        <html lang={params.locale} className="scroll-smooth">
        <body className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
            <NextIntlClientProvider>
                <ThemeBackground/>
                <div className="min-h-screen flex flex-col transition-colors">
                    <Header/>
                    <main className="flex-1 p-8 transition-colors">{children}</main>
                    <footer className="p-4 text-center text-gray-500">
                        © 2025 SkyNet. All rights reserved.
                    </footer>
                </div>
            </NextIntlClientProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
