import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/Header";
import ThemeBackground from "@/components/ThemeBackground";
import { NextIntlClientProvider } from "next-intl";
import Footer from "@/components/Footer";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["400", "700"],
});
const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "SkyNet App",
    description: "Generated by create-program next app",
};

export default async function LocaleLayout({
                                               children,
                                               params,
                                           }: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;

    return (
        <html lang={locale} className="scroll-smooth">
        <body className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
            <NextIntlClientProvider locale={locale}>
                <ThemeBackground />
                <div className="min-h-screen flex flex-col transition-colors">
                    <Header />
                    <main className="flex-1 p-8 transition-colors">{children}</main>
                    <ScrollToTopButton/>
                    <Footer/>
                </div>
            </NextIntlClientProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
